replicaCount: 1

namespace: rocksdb-poc
dataStorageSize: '250Gi'
deploy:
  name: server
pod:
  name: server
  image: docker.io/sagifsqream/rocksdb-server-poc:0.1
  pullPolicy: Always  
  port: 4080
  volumeName: server-data

service:
  name: server
  type: ClusterIP
  port: 4080

  
storageClass:
  name: rocksdb-regionalpd-storageclass

storageClaim:
  name: server-data-claim