apiVersion: batch/v1
kind: Job
metadata:
  name: writer
  namespace: rocksdb-poc
spec:
  template:
    spec:
      containers:
      - name: writer
        image: docker.io/sagifsqream/writer-rocksdb:0.4
      restartPolicy: Never
  backoffLimit: 3