apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pod.name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.pod.name }}
    spec:
      volumes:
        - name: {{ .Values.pod.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.storageClaim.name }}
        
      containers:
        - name: {{ .Values.pod.name }}
          image: "{{ .Values.pod.image }}"
          imagePullPolicy: {{ .Values.pod.pullPolicy }}
          ports:
            - containerPort:  {{ .Values.pod.port }}
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Values.pod.volumeName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  
  